### ISSUE TITLE
Can see HTML5 Cellular on Firefox and Chrome but not Safari

### ISSUE THREAD

**Issue by mciotola** [aidanlane/snapapps#40]
I am using Safari 7.0.4 on Mavericks. Do I need to have Java installed?

http://aidanlane.github.io/snapapps/cellular.html

**Comment by aidanlane** [comment]
Hey @mciotola, can you recheck this, now that @Craxic has pulled in the latest. Erosion of snap?

**Comment by mciotola** [comment]
Opening Cellular HTML 5 on Safari still produces a blank screen, even
though I tried several reloads.

**Comment by aidanlane** [comment]
Thanks Mark- @Craxic, could you have a look at this, thanks!

**Comment by Craxic** [comment]
Hi Guys,

Can anybody with a Mac please test this again?

Thanks!

**Comment by aidanlane** [comment]
It now works for me on Safari 8.0.6- champion!!!
