### ISSUE TITLE
cellular_logo_sm.png missing from generated zip file

### ISSUE THREAD

**Issue by aidanlane** [aidanlane/snapapps#45]
```
Failed to load resource: the server responded with a status of 404 (Not Found)
http://.../cellular_logo_sm.png
```

**Comment by aidanlane** [comment]
Hi @Craxic, can you check if this is still an issue? Thanks!

**Comment by Craxic** [comment]
Hi Aidan,

That file exists in the generated ZIP files. Not sure what the issue is with this, closing it for now.

**Comment by aidanlane** [comment]
Great, thanks mate!

**Comment by Craxic** [comment]
Figured out the issue here, fixed.

**Comment by aidanlane** [comment]
Wow, looks like a big fix- in a nutshell, what was the problem?

**Comment by Craxic** [comment]
Oh, well since there are 3 apps (Cellular, Scribble, Ardrone) using the same code, I needed to make a way for them to add files based on what app is running (e.g the logo). So I had to factor out some stuff. In doing so, I made it much neater and cleaned up some stupid stuff I did.

**Comment by aidanlane** [comment]
That makes sense, great! Thanks again for all your hard work mate :)
