### ISSUE TITLE
Cellular: sprite selector does not take image of selected costume

### ISSUE THREAD

**Issue by mciotola** [aidanlane/snapapps#48]
Cellular: the sprite selector does not take the image of the selected costume; the turtle sprite still appears in the selector, even though the cow was selected. However, the correct image does show up on the stage. See image below:
![screen shot 2015-05-13 at 10 05 59 pm](https://cloud.githubusercontent.com/assets/714256/7626342/6866e40a-f9bc-11e4-8eae-43748017ebd1.png)

**Comment by aidanlane** [comment]
Great, thanks Matt!

**Comment by mciotola** [comment]
Was this change deployed yet? I don't see it.
