### ISSUE TITLE
Do we need to add code snippet to the Cellular index.html for Alexandria interactives?

### ISSUE THREAD

**Issue by mciotola** [aidanlane/snapapps#49]
Do we need to add the below code snippet to the Cellular index.html files to get them to accept parameters as Alexandria interactives? The tutorial implies this, and I am not getting the URL parameter to work yet without doing do.

    (function() {
        "use strict";
        window.onInteractiveLoad = function() {
            var model = getInteractiveParameter('model');
            
            // ...
        }
    }());

**Comment by Craxic** [comment]
Yes, you will indeed need to do this. Unfortunately I no longer have any access to Alexandria so I cannot perform any testing or fixing. @aidanlane?

**Comment by aidanlane** [comment]
Sure, what authcate username?

**Comment by Craxic** [comment]
"rmatt"

**Comment by aidanlane** [comment]
Done :)

**Comment by Craxic** [comment]
Hi Aidan,

Could you please approve interactive "Cellular Test" (62461). Thanks.

**Comment by aidanlane** [comment]
As in "publish"? If so, done :)

**Comment by Craxic** [comment]
Hi Aidan,

OK, I've done some more debugging. Could you please publish "Cellular Test 2" (62476). Thanks.

**Comment by aidanlane** [comment]
Done and I've temporarily made you a publisher.

**Comment by Craxic** [comment]
Hi Aidan,

I'm no longer a publisher so I can't test/fix this right now.

Matt.

**Comment by aidanlane** [comment]
Sorry, I've bumped you back up to publisher.



--

Aidan Lane

Director, Education Technology Lab




Faculty of Information Technology

Monash University, Room H6.80, Caulfield Campus

900 Dandenong Road, Caulfield East, VIC 3145, Australia

+61 3 9905 8471

https://www.alexandriarepository.org




CRICOS Provider: Monash University 00008C

**Comment by Craxic** [comment]
Hi Aidan,

I've noticed that the functionality for Interactive parameters is broken (In the user friendly dialog at least). My last copy of alexandria shows the following code in `/src/wp-content/plugins/alex_interactive/public/assets/js`:

```
    var interactiveForm =
        '<div class="iadd-wrap" id="interactive-add-dialog">' +
            '<div class="iadd-page-wrap iadd-params-page-wrap">' +
```

However in the version served to me, I see:

```
    var interactiveForm =
        '<div class="iadd-wrap" id="interactive-add-dialog">' +
            '<div class="iadd-page-wrap iadd-list-page-wrap">' +
```

It will be broken until this is repaired.

Out of interest, why was it removed? Did I screw something up somewhere?

**Comment by Craxic** [comment]
You can now use Cellular/Scribble as-is in Alexandria. 
* Add new interactive to Alexandria
* Add parameter named "Project" with identifier "project". Set type to "File Inline (attribute value is file contents)".
* Set main HTML file to cellular.html
* Publish the Interactive
* Go to your Module and insert the Interactive! NOTE: Until the above issue with the Interactives plugin is resolved, you will be unable to add any parameters and will instead see a grey screen in the dialog upon pressing "Use". For now, you will need to use the ID of a valid Cellular project file uploaded onto Alexandria in the following fashion: `[interactive 12345 project="Inline: 67890"]` where 12345 is the ID of the Cellular interactive, and 67890 is the ID of the XML Project File.

New release incoming.

**Comment by aidanlane** [comment]
> However in the version served to me, I see that a large div classed with "iadd-params-page-wrap" (shown above) is missing:

Interesting, I'll have a look today, Thanks!

**Comment by aidanlane** [comment]
Looks like someone accidentally removed some code.

I tried patching it with:
```javascript
    // The base HTML of the dialog
    var interactiveForm =
            '<div class="iadd-wrap" id="interactive-add-dialog">' +
                '<div class="iadd-page-wrap iadd-params-page-wrap">' +
                    '<div class="iadd-page iadd-params-page iadd-page-hidden-right">' +
                        '<div class="iadd-title">' +
                            '<div class="iadd-params-back">' +
                                '<a class="button button-large" href="#">' +
                                    '<div class="dashicons dashicons-arrow-left-alt2 iadd-params-back-icon"></div> Back' +
                                '</a>' +
                            '</div>' +
                            '<div class="iadd-params-insert">' +
                                '<a class="button button-large button-primary" href="#">' +
                                    'Insert' +
                                '</a>' +
                            '</div>' +
                            '<span class="iadd-title-text iadd-params-title-text">SUM TITLE</span>' +
                        '</div>' +
                        '<div class="iadd-params-container">' +
                            '<table class="iadd-params-table">' +
                            '</table>' +
                        '</div>' +
                    '</div>' +
                '</div>' +
                '<div class="iadd-page-wrap iadd-list-page-wrap">' +
                    '<div class="iadd-page iadd-list-page">' +
                        '<div class="iadd-title" style="padding-left: 16px;">' +
                            '<input type="text" placeholder="Search" class="iadd-search-bar"/>' +
                            '<span class="iadd-title-text iadd-list-title-text">' + allInteractivesText + ' </span>' +
                        '</div>' +
                        '<div class="iadd-results-container">' +
                            '<table class="iadd-results" id="interactive-results">' +
                            '</table>' +
                        '</div>' +
                        '<div class="iadd-close">' +
                            '<a href="#" class="button button-large iadd-close-btn">Close</a>' +
                        '</div>' +
                    '</div>' +
                '</div>' +
            '</div>';
```

But it still doesn't work- the params page appears solid black.

@tuanmh, could you have a look at it ASAP for me? Thanks!

**Comment by tuanmh** [comment]
sure, I will look at this tmr.

**Comment by aidanlane** [comment]
Thanks Tuan!

**Comment by tuanmh** [comment]
@aidanlane could you please grant me permission to view/edit Matt's interactive: interactive id = 62546

**Comment by aidanlane** [comment]
No probs, for `tuan` or `tuanm`?

**Comment by tuanmh** [comment]
```tuanm``` please

**Comment by aidanlane** [comment]
done :)

**Comment by tuanmh** [comment]
This is the window I got after fixing (hopefully) the bug:

![image](https://cloud.githubusercontent.com/assets/3193353/7717647/2ddf028c-fee8-11e4-935c-6378280298cf.png)

Can anyone confirm this is correct?

**Comment by aidanlane** [comment]
Can you set the params when clicking "Use" (from Add Interactive dialog)?

**Comment by tuanmh** [comment]
Ah here is that window:

![image](https://cloud.githubusercontent.com/assets/3193353/7717710/2ca9d1e8-fee9-11e4-97b2-88ac5f03bc5b.png)

**Comment by aidanlane** [comment]
That's it, perfect!

**Comment by tuanmh** [comment]
Multiple params: 

![image](https://cloud.githubusercontent.com/assets/3193353/7717743/b05cb15e-fee9-11e4-9fd7-c6c9d860e227.png)

**Comment by aidanlane** [comment]
Nice! (and to you too @Craxic)

**Comment by mciotola** [comment]
For SnapApps, I think we need to be able to enter in a long URL rather than
a few numbers. It is not clear how to do so. Would that be single line
text? Do the SnapApps know what to do with it?

**Comment by aidanlane** [comment]
Sorry Mark, what do you mean?

For SnapApp projects, you can simply upload it's XML file via the GUI.

**Comment by mciotola** [comment]
Just to be clear, the goal is to enter a very basic Cellular interactive
once, then specify an input URL to turn the basic interactive into a
particular simulation (e.g. grazing, ants, bushfire with the appropriate
blocks, costumes, stage-painting, etc.) for each different learning module.
This will greatly reduce ePub size and hopefully improve overall Alexandria
performance.

Don't I need to enter parameters in the interactive short code? If I
specified an XML file path, where would that file be located?

[image: Inline image 2]
Or how do I specify an XML file in the Parameters GUI?


[image: Inline image 1]

**Comment by mciotola** [comment]
Or instead of a URL, I have an exported XML file. Yet I am still not sure
how to enter the XML file in the Interactive entry view:
[image: Inline image 1]

**Comment by mciotola** [comment]
OK, I think I get it. I upload the XML file to the media library, and
include it as an "inline" file. Correct? (See below).
[image: Inline image 1]

**Comment by mciotola** [comment]
Yes, now this works for me. Thanks!

**Comment by aidanlane** [comment]
Yep, that's it :))
