### ISSUE TITLE
Cellular HTML5: Flat Design alway present when Exporting to ZIP

### ISSUE THREAD

**Issue by mciotola** [aidanlane/snapapps#50]
Cellular: the flat design is alway present when Exporting to ZIP, even when the "Flat design" box is unchecked in the Widget menu. The problem is that the Flat design is harder to use. For example, the "radius(cells)" and "value" labels beneath the stage are in white text against a white background.

See below menu:
![flat_design_unchecked](https://cloud.githubusercontent.com/assets/714256/7645837/f7432770-fa6f-11e4-87d0-7feed66a1689.png)

Then the Interactive displays:
![embedded_flat_design](https://cloud.githubusercontent.com/assets/714256/7645840/00347d34-fa70-11e4-8a5c-4f04838ac0b0.png)

**Comment by aidanlane** [comment]
Ah, that was my decision a while ago. It was because the flat look suited the web pages of Alexandria better. However, if it's a real usability issue, then we could remove this behaviour. What do you think @mciotola and @Craxic ?

**Comment by mciotola** [comment]
The Flat design certainly is more consistent with Alexandria's look & feel.
If the Flat design was tweaked a bit (i.e. change white type to dark type,
contrast other features better, etc.), it would be clearer to users. Until
then, it will be confusing for beginning users.

**Comment by aidanlane** [comment]
@mciotola: very true. @Craxic: what do you think?

**Comment by Craxic** [comment]
Hey everyone. It's my bad for making the text always white for the drawing bar. I've fixed that up. 
I agree that the flat UI is a much better fit for Alexandria. However, the flat UI style is really hideous and neglected. It's just a poorly designed re-skinning of the original style where everything is more difficult to use. So long as the user doesn't have to edit anything, I think we should keep it. If the user might want to look at the code and try some other things, it should probably go. Up to you @aidanlane.

Sorry for closing the issue, didn't mean to.

**Comment by aidanlane** [comment]
Okay, let's try this: revert to not forcing flat and just use the current setting.
Thanks for your patience.

**Comment by aidanlane** [comment]
Ps. Good idea with the 'waiting reply' status :)

**Comment by aidanlane** [comment]
Perfect, thanks :+1:

**Comment by mciotola** [comment]
Matt,

The Flat design is looking a lot better!

One improvement would be to add grey shading behind the sprite number field.

Another improvement would be to contrast the Cancel and OK buttons in the
sprite editing window.


Mark
