### ISSUE TITLE
Cellular HTML5: cannot delete variable

### ISSUE THREAD

**Issue by mciotola** [aidanlane/snapapps#51]
Cellular HTML5: cannot delete variables. Clicking the "Delete A Variable" button does not have any effect, even when the box to the left of the variable is checked. (Yes, I misspelled the variable name, which is why I want to delete it.)

![cannot_delete_variable](https://cloud.githubusercontent.com/assets/714256/7646896/cfdd0e34-fa7f-11e4-86cf-27fae1a8be12.png)

**Comment by mciotola** [comment]
A bit of progress. When I click "Delete a Variable", I get a menu (see image below) with the variable names to delete. However, it does not actually delete the variable. In contrast, using this pop-up menu to delete cell attributes does seem to work.

![delete_var_menu](https://cloud.githubusercontent.com/assets/714256/7647553/dd9f1d30-fa8b-11e4-9d2e-f100bcfba32e.png)

**Comment by mciotola** [comment]
There is still a problem. When I "Delete a Variable" and choose a variable to delete, that variable disappears from the stage. However, it still remains in the Variables block list, at least for awhile. This will make the user think the variable has not actually been deleted, even if it has been.

For example, I created then deleted "vartest2" and "vartest3". The names no longer appear on the stage, but do appear in the Variables blocklist (see two images below).


![cellular_html5_var_del-1](https://cloud.githubusercontent.com/assets/714256/7664921/807f0e92-fb55-11e4-8531-75307414b135.png)
![cellular_html5_var_del-2](https://cloud.githubusercontent.com/assets/714256/7664922/84420f20-fb55-11e4-8504-7e0abc77b4c1.png)

**Comment by Craxic** [comment]
Hi Mark,

I'm unable to reproduce this issue. Could you please specify the types of these variables (global, for each instance of this sprite). I can't see any issue with either.

Please let me know when you find a way to reliably reproduce this bug. Sorry I can't help any further.

**Comment by mciotola** [comment]
The problem is gone! Which means it was likely related to something else you recently fixed.
