### ISSUE TITLE
Cellular HTML5: need default cell attribute? 

### ISSUE THREAD

**Issue by aidanlane** [aidanlane/snapapps#53]
It's a pain for first time users if not.
What did the desktop version do?

**Comment by aidanlane** [comment]
Champion!

"default" as a name works for me- how about you @mciotola and @berndmeyer?

**Comment by berndmeyer** [comment]
not sure I get the context of the question (sorry, unable to log onto
Github, my password is on my laptop which will only return to me tomorrow :)
Anyway, it appears the issue has been closed already.

Matt, thanks for helping out with this.
It's about time we closed off this branch (cellular / scribble) but do be
able to do that we first need to get them into Alexandria...

Best,

Bernd

**Comment by aidanlane** [comment]
Hi Bernd,

It had to do with the need for a default cell attribute in Cellular.

The desktop version had one called "CellAttr1", which meant that the user could start using it straight away, including paining the default state of it.

The HTML version didn't have this at all. So Matt added it.
The question is though: what should it be called? Currently it's "default".
Should it instead be "Default Attribute", "Default Cell Attribute" (too long!?), "CellAttr1" (cryptic?!).

Thanks, A

**Comment by berndmeyer** [comment]
"Default" works for me. Probably not worth worrying too much about? You
won't find a name that suits all.

B.

**Comment by mciotola** [comment]
I liked "CellAttr1", unless it works to spell it out. Default implies certain preset qualities that cannot be changed unless a new attribute is created.

**Comment by mciotola** [comment]
After reviewing the Flat design, I am strenuously for "CellAttr1".
Although the pulldown menu below the stage has no label, "CellAttr1"
indicates the purpose of that menu.

**Comment by aidanlane** [comment]
I agree with "CellAttr1".
An added (albeit small) benefit: it provides a nicer bridge from the desktop version.

Matt- when would you have a chance to work on this again? Thanks, A

**Comment by aidanlane** [comment]
Also, it should be selected by default in the combo-box so that user can draw with it straight away.
Oh and can you set the colour of it to red, instead of grey? Thanks Matt!

**Comment by aidanlane** [comment]
Thanks Matt!
