### ISSUE TITLE
Cellular HTML5: merge in latest version of snap

### ISSUE THREAD

**Issue by aidanlane** [aidanlane/snapapps#54]
the latest version seems to seems to make it easier to bundle in costumes to help users get started faster

**Comment by Craxic** [comment]
My mistake, actually closed in 9d85d2d5676cc5a32aae0588af154b08d63d33ff

**Comment by aidanlane** [comment]
Thanks!

@mciotola, are there any images wpthat you'd like included by default?

**Comment by mciotola** [comment]
Yes. What is the best file format?  GIF?

**Comment by aidanlane** [comment]
I'd recommend PNG. Also, we need to be careful of copyright (as usual :)

**Comment by mciotola** [comment]
Can I assume that we can use any image already included in the desktop
version of Cellular?

**Comment by mciotola** [comment]
I meant in the examples from the desktop version of Cellular?

**Comment by aidanlane** [comment]
err- can you check? just to be absolutely sure :)
