### ISSUE TITLE
Cellular HTML5: can costumes numbers be explicitly displayed?

### ISSUE THREAD

**Issue by mciotola** [aidanlane/snapapps#55]
Cellular HTML5: can costumes numbers be explicitly displayed?

For example, at least one block refers to costume number, which is extremely useful in calculations and costume sensing and selection. See below:
![costume_](https://cloud.githubusercontent.com/assets/714256/7660941/6f458202-fb03-11e4-90fb-c7ceae31f71f.png)
In the desktop version of Cellular, costume numbers were explicitly displayed:

![cellullar_desktop_costume_numbering](https://cloud.githubusercontent.com/assets/714256/7660984/aa5adc48-fb03-11e4-816b-b6dd5ad4a787.png)
However, in the HTML5 version, not only are costume numbers not shown, but the turtle costume does not seem to be deletable (or alterable), so the actual numbering might be confusing.
![celluylar_html5_costume_numbering](https://cloud.githubusercontent.com/assets/714256/7661044/3b0cde4e-fb04-11e4-8308-5f742ae1d780.png)

**Comment by aidanlane** [comment]
Hehe, thanks :)
