### ISSUE TITLE
Cellular HTML5: spraypainting for attribute painting

### ISSUE THREAD

**Issue by mciotola** [aidanlane/snapapps#62]
Cellular HTML5: 

I feel like a professional whiner! Yet here is another enhancement request.

The desktop version of Cellular had a default "spraypaint" (airbrush) effect attached to its paintbrush (see image below). The HTML5 version lacks this. I realize that the intensity control may be a substitute, but it is difficult to have multiple intensities in the same clump of an attribute.

![cellular_html5_attribute_painting](https://cloud.githubusercontent.com/assets/714256/7693405/b6f0e04a-fd85-11e4-9ef2-86457d07b17d.png)

**Comment by mciotola** [comment]
Correction: there already is a slight airbrush effect; could this be increased?

**Comment by aidanlane** [comment]
Is this a matter of adjusting the 'spread' value from desktop version (see the 'Make a cell attribute' dialog).

**Comment by Craxic** [comment]
Mark, is this what you mean?

![Brush hardness](http://striegle51839.c4.cmdwebsites.com/blog/wp-content/uploads/2012/02/hardness1.jpg)

**Comment by mciotola** [comment]
Partly yes. Perhaps 25% would be even better. It is also helpful if an area
gets darker the longer one holds the brush over it (as with the desktop
version).

**Comment by Craxic** [comment]
In the latest version of cellular, the brush tool has a hardness parameter. You can use this to make the brush more or less blurry, as you desire.

**Comment by aidanlane** [comment]
Great, thanks Matt!
