### ISSUE TITLE
Cellular HTML5: neighbor block question else issue

### ISSUE THREAD

**Issue by mciotola** [aidanlane/snapapps#64]
Cellular HTML5: 

I am trying to replace the "# alight in nbr cells" and the "match in cell right?" desktop Cellular blocks (see below)

![cellular_desktop_bushfire_question](https://cloud.githubusercontent.com/assets/714256/7694118/98df9208-fd90-11e4-93f9-f331556f8e46.png)
with neighbor blocks in the Cellular HTML5 version (see below)
![cellular_html5_neighbor_blocks](https://cloud.githubusercontent.com/assets/714256/7694128/b0978054-fd90-11e4-8da7-340c8ab91564.png)

How should I proceed? (See below for Cellular desktop neighbor blocks). There are a lot of legacy blocks with a pulldown menu for costume, but the HTML5 blocks simply say "object". Is there a trick for "object" to refer to a specific costume for simulations that involve multiple object/costume types?
![cellular_desktop_neighbor_blocks](https://cloud.githubusercontent.com/assets/714256/7694163/51d6d924-fd91-11e4-8e95-49cb33a87af7.png)

**Comment by mciotola** [comment]
I'm trying to figure out a way to use Sensing or Object blocks to help, but I don't get it yet.

**Comment by aidanlane** [comment]
Hi @Craxic, have you any suggestions using the existing blocks? or does this also need dev work?
