### ISSUE TITLE
Cellular HTML5: do we need breed and die control blocks?

### ISSUE THREAD

**Issue by mciotola** [aidanlane/snapapps#65]
Cellular HTML5: 

The desktop version of Cellular contains special "breed" and "die" control blocks (see below image) that I cannot find in the HTML5 version. Do we need these blocks in the HTML5 version, or is there some clever way to use other blocks to accomplish the same?

![cellular_desktop_control_blocks](https://cloud.githubusercontent.com/assets/714256/7696238/f2ec1e3c-fdaf-11e4-8024-65de47c7679a.png)

**Comment by aidanlane** [comment]
I think that the 'clone' block replace them:
![image](https://cloud.githubusercontent.com/assets/1817949/7696286/ef1f03fc-fe3e-11e4-8b86-e0eebcd35b4e.png)
