### ISSUE TITLE
Cellular HTML5: images get fuzzy when growing or shrinking

### ISSUE THREAD

**Issue by mciotola** [aidanlane/snapapps#66]
Cellular HTML5:

Images get fuzzy when growing or shrinking (see tool bar).

![cellular_html5_grow-shrink-tools](https://cloud.githubusercontent.com/assets/714256/7696648/fe58d428-fdb3-11e4-951a-a89080303d28.png)

 I can live with this, but I have a hunch Bernd will object. For instance, this original palm:

![palmtree2](https://cloud.githubusercontent.com/assets/714256/7696548/41d91ac4-fdb3-11e4-8892-af971fbbbbe6.gif)

becomes the following (large, small, individual large). Perhaps there is an anti-aliasing setting that can be changed?
![screen shot 2015-05-18 at 8 49 43 pm](https://cloud.githubusercontent.com/assets/714256/7696587/81108858-fdb3-11e4-89f6-f4f20e2d8b68.png)
![cellular_html5_fuzzy_enlargedtrees](https://cloud.githubusercontent.com/assets/714256/7696588/82f50414-fdb3-11e4-9876-66a292548a5b.png)

![cellular_html5_fuzzy_reduced_trees](https://cloud.githubusercontent.com/assets/714256/7696622/c7f6365a-fdb3-11e4-9325-6da49bdc0d7b.png)

**Comment by Craxic** [comment]
Hi Mark,

This is the functionality of the grow and shrink buttons. It simply scales the image up or down by a small percentage each time the button is pressed. You can expect the image to become very blurry.

Please use the set scale block if possible.

Matt.

**Comment by aidanlane** [comment]
Yep, that makes sense from an image editing experience.

The desktop version had a 'resize this sprite' on the agent's context menu. Does the web version have an analogue?

**Comment by mciotola** [comment]
I think part of the problem is that I have to click the shrink button in the HTML5 version about 25 times to get the same reduction as clicking it roughly about 5 times in the desktop system. So in the new system, the image will be about 5 times fuzzier.

Matt, I will try the set scale block tomorrow.

**Comment by mciotola** [comment]
Matt,

Where do I find the "Set Scale" block? That would be very useful, say, if I could automatically resize a costume to fit in a single cell, or a single cell vertically, etc.

I did find the "set size to __%" is that what you meant? Although it does not seem to resize with reference to cell size, it does seem to preserve image crispness, which is also very helpful.
![cellular_html5](https://cloud.githubusercontent.com/assets/714256/7738080/a35b5bce-ff05-11e4-8bfe-82b81df23f84.png)

**Comment by Craxic** [comment]
Hi Mark,

You'll need to use the set size block to set the size of all of the sprites. Images are resized relative to their original image size, 100% being 1:1.

Note that if you adjust the number of cells showing on the stage, the sprites will resize themselves appropriately.

I will see what I can do about creating a block to scale the sprite to cell size.

Matt.

**Comment by Craxic** [comment]
Hey Mark,

I've added a new block called "scale to cell size" under "looks" in commit 83866f0.

Thanks,
Matt.

**Comment by mciotola** [comment]
Thanks! I'll try it out.

**Comment by Craxic** [comment]
Hey Mark,

If you want me to make some more blocks for you (I think that's what you wanted to talk about right?), just add an issue and I'll get to it.

Matt.
