### ISSUE TITLE
Cellular HTML5: can't get "distance to" block to work

### ISSUE THREAD

**Issue by mciotola** [aidanlane/snapapps#67]
Cellular HTML5: 

I have been trying to get the ant simulation to work properly. However, I can't get "distance to" block to work. In the desktop sim, it gets pointed to "Sprite 44". However, in the HTML5 version, the block just lets me point "Type 2" (the anthill sprite), mouse or close. Since there is only one anthill, "Type 2" should work fine for this particular sim. 

However, all of the ants keep moving to the upper top corner and won't leave. I even sprayed some pheremone to get them to move to the nest (see below, although some of the pheremone has worn off in that image).

![cellular_html5_distance-to_block](https://cloud.githubusercontent.com/assets/714256/7738651/c070ab0a-ff0b-11e4-8724-4c99e3a5387b.png)

![cellular_html5_distance-to_block](https://cloud.githubusercontent.com/assets/714256/7738658/c3a59c22-ff0b-11e4-9ac1-49a3d9022818.png)

**Comment by Craxic** [comment]
Hi Mark,

Your images are not working correctly. Would you also be able to provide the project file too (for HTML5 Cellular)?

Thanks,
Matt.

**Comment by mciotola** [comment]
I sent the project file via email. Should I send gif format images instead if png format in the future?

**Comment by aidanlane** [comment]
Related to #77, but not exactly the same. @Craxic, can you work on #77 first, thanks!

**Comment by aidanlane** [comment]
Brilliant! In a nutshell, what was the big?
Thanks!!

**Comment by Craxic** [comment]
No big deal, I just had forgotten about these blocks and so they were using the hidden "prototype" sprite for their calculations. Both this block ("point to") and the "distance to" block both use a function called "getOtherObject" to convert an object name to an actual object. So I just moved my changes (from 774f5052f24b59c6b2ec90c3319619c92ce8a387) out of the "distance to" block and into that function instead.

**Comment by mciotola** [comment]
Hi guys,

Let me know when this gets deployed. (I tested today, but did not see the
change).

Also, will we be able to specify by sprite number, sprite type or just
costume type?


Mark

**Comment by aidanlane** [comment]
deployed just now :) be sure to force a refresh in your browser when loading it.

**Comment by aidanlane** [comment]
> Also, will we be able to specify by sprite number, sprite type or just costume type?

Not sure- @Craxic ?

**Comment by aidanlane** [comment]
> No big deal, I just had forgotten about these blocks and so they were using the hidden "prototype" sprite for their calculations.

Ah, thought so :)

> Both this block ("point to") and the "distance to" block both use a function called "getOtherObject" to convert an object name to an actual object. So I just moved my changes (from 774f505) out of the "distance to" block and into that function instead. Doing it this way, it looks like it'll cover some other bases too.

Brilliant! Thanks!

**Comment by mciotola** [comment]
Yes, this works for me now. Thanks!

**Comment by aidanlane** [comment]
Fantastic, thanks @Craxic for getting this working!
