### ISSUE TITLE
Cellular HTML5: having graphics troubles

### ISSUE THREAD

**Issue by mciotola** [aidanlane/snapapps#68]
Cellular HTML5: I am having graphics troubles. I can't get sprites to show up. There is a weird smearing going on of costume icons (see image below).

![cellular_html5_weirdness](https://cloud.githubusercontent.com/assets/714256/7763229/d02d408e-fff2-11e4-8a5b-9ac6a637446f.png)

**Comment by aidanlane** [comment]
Wow, that is weird! @Craxic- any suggestions?

**Comment by mciotola** [comment]
It happens when:

I try to enter in the number of sprites (e.g. 50). The number doesn't change (and no sprites appear), so I click enter in the field. It still doesn't change, so I click enter again, then the smearing occurs.

**Comment by mciotola** [comment]
This is serious! I can't set the sprite number in any Cellular HTML5 simulations so far. (I was able to do so fine yesterday). I was trying to build my own blocks earlier today, but this simulation doesn't have any custom blocks.

**Comment by Craxic** [comment]
Hi Mark. 

Sorry about this issue, it's fixed now. Unfortunately there are a few additional steps you need to take with your project files:

* Export project to file
* Open project XML in a text editor
* Find `scale=`. You'll probably see a huge number like `scale="1000000"`. 
* Replace all of `scale="<insert scale here>"` with `scale="1"`
* Save file.
* Import project into Cellular.

If you want to, just send me the project files and I can do it for you.

Really sorry about this bug!
