### ISSUE TITLE
Cellular HTML5: can sprites automatically be placed in cells when populated?

### ISSUE THREAD

**Issue by mciotola** [aidanlane/snapapps#72]
Cellular HTML5: 

Can sprites automatically be placed in cells when populated?  E.g. when entering a number in the sprite box beneath the stage (see below).
![cellular_desktop_sprite_pop_entry](https://cloud.githubusercontent.com/assets/714256/7781346/f51e64d6-00a1-11e5-80e1-3ec10786eada.png)
This already happens in the desktop version, but in the HTML5 version, the sprites often cross cell borders, even when small (compare images: 1st is desktop, end is HTML5)
![cellular_desktop_sprites_in_cells](https://cloud.githubusercontent.com/assets/714256/7781351/0f435baa-00a2-11e5-92ee-9e079688ce25.png)
![cellular_html5_sprites_cross_cells](https://cloud.githubusercontent.com/assets/714256/7781370/6efc836e-00a2-11e5-978b-59e06a3dcfb0.png)
This would help with the resizing issue as well.

**Comment by Craxic** [comment]
Great idea, done!
