### ISSUE TITLE
Cellular HTML5: adjusting loop cycle timing

### ISSUE THREAD

**Issue by mciotola** [aidanlane/snapapps#73]
Cellular HTML5: 

In the desktop version of Cellular, top-level loop cycles seemed to progress at about 5 cycles per second. This made for a nicely watchable animation.

In contrast, in the HTML5 version of Cellular, top-level loop cycles seemed to progress at roughly about 20 cycles per second.  This is quite hard for the eye to follow. Adding a "wait 0.2 second" control block to scripts helps a lot, yet I wonder if there should be some sort of 0.2 second default cycle time.

This is a bit of a "fine-tuning issue", but it is significant for the user experience.

**Comment by Craxic** [comment]
Hi Mark,

Is this OK for you?
![Wait block](https://cloud.githubusercontent.com/assets/4537985/7782321/05075dea-0155-11e5-9c36-ad4b56162dca.png)

Matt.

**Comment by mciotola** [comment]
Yes, let's go ahead and try that.

**Comment by Craxic** [comment]
That block already exists under "Control". Is it OK to close this?

Thanks!

**Comment by mciotola** [comment]
Cellular HTML5 seems to run much more quickly than desktop Cellular, so the
animation timing will typically need to be adjusted by the user. However,
this issue is minor, so go ahead and close it.

**Comment by Craxic** [comment]
Thanks Mark!
