### ISSUE TITLE
Cellular HTML5: varFrames error

### ISSUE THREAD

**Issue by mciotola** [aidanlane/snapapps#74]
I had saved a Cellular HTML5 sim, but when I tried to re-open it, I received the below varFrames error, and can no longer open that simulation (ants). I had redone the ant simulation from scratch, so there is no chance that it is correct from the scale error.
![cellular_html5_var_error](https://cloud.githubusercontent.com/assets/714256/7781787/1b21099a-00ac-11e5-9972-77f9eadf8de3.png)

**Comment by Craxic** [comment]
Hi Mark, 

I need a project file or some steps I can take to reproduce this bug. Until then it's going to make fixing this almost impossible.

Thanks,
Matt.

**Comment by mciotola** [comment]
I go to import file. I choose the file, and I get the error. Perhaps
something weird happened when I saved the file in Cellular.

Unfortunately, I cannot pull out the file. I even tried to get the URL in
history, but it didn't show up.

I guess we can just treat this as a one-time event and ignore it unless it
happens again.

**Comment by Craxic** [comment]
Hi Mark,

Please visit https://aidanlane.github.io/snapapps/project_debug.html and provide me with the project file.

Thanks!

**Comment by mciotola** [comment]
All I get is a blank screen.

**Comment by mciotola** [comment]
The varFrames error happened again, with a new file called ants2 (see below image). Matt, I was able to export the XML file this time and I emailed it to you.

![cellular_html5_ants2_var-error](https://cloud.githubusercontent.com/assets/714256/7782460/7f92424c-00cd-11e5-8dec-3aede38362ad.png)

**Comment by Craxic** [comment]
Mark,

Would you be able to try this again please?

Thanks,
Matt.

**Comment by mciotola** [comment]
I can open my ants Cellular project without the varFrames error. Thanks!

**Comment by aidanlane** [comment]
Brilliant! Happy to close this Mark?
