### ISSUE TITLE
Costumes and Sounds missing / broken

### ISSUE THREAD

**Issue by aidanlane** [aidanlane/snapapps#75]
Click File -> Costumes... doesn't work:

```
Failed to load resource: the server responded with a status of 404 (Not Found)
     IDE_Morph.getURL @ gui.js:4255
morphic.js:7598 Uncaught TypeError: this.text.split is not a function
```

**Comment by Craxic** [comment]
The code was relying on the server to list files in a directory for them in a specific format. That doesn't happen on gh-pages, so I altered it.

**Comment by aidanlane** [comment]
Clever workaround, thanks Matt!
