### ISSUE TITLE
Cellular HTML5: attribute stage painting should reset itself when restarting?

### ISSUE THREAD

**Issue by mciotola** [aidanlane/snapapps#76]
Cellular HTML5: 

Should the attribute stage painting should reset itself when the simulation restarts?

**Comment by aidanlane** [comment]
Is that what's happening now? What happens in the Desktop version?

**Comment by aidanlane** [comment]
@mciotola and @Craxic, would you both be able to check this for me? What happens in the desktop version?

**Comment by Craxic** [comment]
Hi Aidan,

Cellular on the desktop version does NOT reset the cell attributes when the simulation is stopped or started. This is the same functionality as in the HTML5 version.

**Comment by aidanlane** [comment]
Thanks for checking that Matt.
I believe that we should keep it the same. Closing issue.
@mciotola, reopen if you beg to differ :stuck_out_tongue_winking_eye:

**Comment by mciotola** [comment]
I'm not sure, but if I think different, I will open a new ticket for a feature enhancement. At least as long as the user does not save the changes then re-opening has the same effect as resetting.

**Comment by aidanlane** [comment]
@berndmeyer, do you have any thoughts on this?
