### ISSUE TITLE
Cellular HTML5: "distance to" block reports incorrect distances

### ISSUE THREAD

**Issue by mciotola** [aidanlane/snapapps#77]
Cellular HTML5: 

The "distance to" block reports incorrect distances. For example, in the ants simulation shown below, the "distance to" block is set to "colony" which is the yellow block sprite in the lower left corner. Yet the ants seem to show their distance to some point in the center right. Aidan thinks this is because the "distance to" block might be pointing to the default sprite location. We need this block for several of the example simulations.
![cellular_html5_ants_distance_2](https://cloud.githubusercontent.com/assets/714256/7804730/7cd5ed56-031b-11e5-941d-30649dfba365.png)

**Comment by aidanlane** [comment]
Awesome!!! :+1:
