### ISSUE TITLE
 How do I get darker attribute colours?

### ISSUE THREAD

**Issue by mciotola** [aidanlane/snapapps#84]
Hi Matt,

How do I get darker attribute colours?

For example, in the Bacteria simulation, your simulation shows gradients and values up to 100, but I seem to only be able to draw up to 10 (i.e. changing the value field of the attribute over 10 seems to have no effect.

Mark

**Comment by Craxic** [comment]
Hey mark,

There are two fields in the list of cell attributes. One is the minimum value, one is the maximum value. I'll make this more clear, thanks for the issue.
