### ISSUE TITLE
Cellular HTML5: User's blocks cannot be edited

### ISSUE THREAD

**Issue by cienciascontic** [aidanlane/snapapps#98]
Once you have created a block, if you do right click over it and select "Edit..." the blocks bar becomes freezed and you're not able to do anything else until you click on another block category.
This bug is present no matter the version, the language nor the browser.
I tried the same in Snap and it works fine, the block picture windows pops up and let you edit your block.

**Comment by aidanlane** [comment]
Thanks for raising @cienciascontic  👍

**Comment by aidanlane** [comment]
Thanks @Craxic!
Fixed via https://github.com/aidanlane/snapapps/commit/663a551d38abe60798bd77df7f3186340fa1feec (not sure why that's not appearing in the GitHub log here?)
