### ISSUE TITLE
Cellular HTML5: Examples cannot be opened

### ISSUE THREAD

**Issue by cienciascontic** [aidanlane/snapapps#99]
If you try to open one of the examples that come with Snap (Animal game, Codification, copter, etc.), when you click on the name and then click the "Open" button, you get a prompt with the following error message: "Load failed: TypeError: Cannot read property 'ChildrenNamed' of null".
See attached screenshot.
![screenshot-opening-example-in-cellular](https://user-images.githubusercontent.com/6078186/29758302-bae61aa6-8b88-11e7-8935-975bd99801fe.png)

**Comment by aidanlane** [comment]
Wow, thanks @Craxic!
